enable: true
book-title: "Book Score Book"
book-author: "%player_name%"
page-1:
  - "Book Score Board"
  - "Name: %player_name%"
  - "Workd: %player_world%"
page-2:
  - "Example Page 2"
  - "ยง9example colorful message"
